config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: %i[index show new create] do
    resources :comments, only: :create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    ServerCaller.call('post', "posts/#{params[:post_id]}/comments", comment_params)
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    { comment: params.require(:comment).permit(:name, :body).to_h }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    posts = ServerCaller.call('get', 'posts')['posts']
    @posts = posts ? posts.sort_by { |hsh| hsh[:id] }.reverse : []
  end

  def show
    @post = ServerCaller.call('get', "posts/#{params[:id]}")
    comments = ServerCaller.call('get', "posts/#{params[:id]}/comments")['comments']
    @comments = comments ? comments.sort_by { |hsh| hsh[:id] }.reverse : []
  end

  def create
    response = ServerCaller.call('post', 'posts', post_params)
    if response['errors']
      @errors = response['errors']
      render :new
    elsif response == {}
      @errors = ['Server not working']
      render :new
    else
      redirect_to post_path(response['id'])
    end
  end

  def new; end

  private

  def post_params
    { post: params.require(:post).permit(:title, :body).to_h }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Japanese Blog</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://yannklein.github.io/japan-pictograms/japan-pictograms.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/posts/index.html.slim
div id="content" class="site-content"
  main id="main" class="site-main inner"
    div class="post-feed"
      - @posts.each do |post|
          article class="post"
            header class="post-header"
              h2 class="post-title"
                = link_to post['title'], post_path(post['id'])
              div class="post-meta" Published on #{post['created_at'].to_date.strftime("%Y %B %d")}
            div class="post-content"
              p #{post['body'].split("\n").first}
            p class="read-more"
              = link_to 'Keep reading <span class="icon-arrow-right" aria-hidden="true"></span>'.html_safe, post_path(post['id']), class: 'read-more-link'

app/views/posts/new.html.slim
div id="content" class="site-content"
  main id="main" class="site-main inner"
    - if @errors
      - @errors.each do |error|
        p style="color: red;" = error
    = simple_form_for :post, url: posts_path do |f|
      = f.input :title, as: :string
      = f.input :body, as: :text
      = f.submit

app/views/posts/show.html.slim
div id="content" class="site-content"
  main id="main" class="site-main inner"
    article class="post post-full"
      header class="post-header"
        h1 class="post-title"
          = @post['title']
        div class="post-meta"
          | Published on #{@post['created_at'].to_date.strftime("%Y %B %d")}
      div class="post-content"
        = @post['body']
  div
    - if @errors
      - @errors.each do |error|
        p style="color: red;" = error
    = simple_form_for :comment, url: post_comments_path(@post['id']), remote: true do |f|
      = f.input :name, as: :string
      = f.input :body, as: :text
      = f.submit
  div class="comments"
  - @comments.each do |comment|
      div class="comment-block"
        div class="comment-title"
          div class="comment-name" = comment['name']
          div class="comment-date" = comment['created_at'].to_datetime.strftime("%Y %B %d %H:%M")
        div class="comment-body"
          = comment['body']

app/views/shared/_branding.html.slim
header id="masthead" class=""
  p class="site-logo"
    = link_to '<span class="jpic jpic-hanami"></span>'.html_safe, root_path
  h1 class="site-title"
    = link_to 'Japanese Blog', root_path
  p class="site-description" Your portal to Japan

app/views/shared/_header.html.slim
header id="masthead" class="site-header bg--loaded"
  div id="header-bg" class="site-header-bg" style="background-image:url(https://resources.matcha-jp.com/resize/720x2000/2020/01/10-94749.jpeg)"
  div class="site-header-scroll"
    div class="site-header-inside"
      div class="site-header-vertical"
        == render 'shared/branding'
        == render 'shared/navigation'

app/views/shared/_navigation.html.slim
nav id="main-navigation" class="site-navigation" aria-label="Main Navigation"
  div class="site-nav-wrap"
    div class="site-nav-inside"
      ul class="menu"
        li class="menu-item"
          = link_to '<span class="jpic jpic-itsukushima"></span> Home'.html_safe, root_path
        li class="menu-item"
          = link_to '<span class="jpic jpic-byoin"></span> New Post'.html_safe, new_post_path
      div class="social-links"
        = link_to '<i class="fab fa-twitter"></i><span class="screen-reader-text">Twitter</span>'.html_safe, 'https://twitter.com/pdalber'
        = link_to '<i class="fab fa-linkedin-in"></i><span class="screen-reader-text">LinkedIn</span>'.html_safe, 'https://www.linkedin.com/in/paulodal/'
        = link_to '<i class="fab fa-github"></i><span class="screen-reader-text">GitHub</span>'.html_safe, 'https://github.com/Naokimi'
        = link_to '<i class="fab fa-medium-m"></i><span class="screen-reader-text">Medium</span>'.html_safe, 'https://medium.com/@phdalberti'
button id="menu-toggle" class="menu-toggle"
  span class="jpic jpic-ninja menu-icon"
  span class="screen-reader-text" Menu